@auction_site_api_HostAddress = http://localhost:5220/api

### testuser1
POST {{auction_site_api_HostAddress}}/users/register
Content-Type: application/json

{
    "username": "testuser1",
    "email": "testuser1@example.com",
    "password": "P@ssword!"
}

### testuser2 vars
@userId2 = 019ca10c-acbe-72cb-93cb-067a325797d9

### Register testuser2
POST {{auction_site_api_HostAddress}}/users/register
Content-Type: application/json

{
    "username": "testuser2",
    "email": "testuser2@example.com",
    "password": "P@ssword!"
}

### Login testuser2
POST {{auction_site_api_HostAddress}}/users/login
Content-Type: application/json

{
  "usernameOrEmail": "testuser2",
  "password": ""
}
### Disable testuser2
PUT {{auction_site_api_HostAddress}}/users/{{userId2}}
Content-Type: application/json

{
  "isActive": true,
  "isAdmin": false
}

### Delete tesuser
DELETE {{auction_site_api_HostAddress}}/users/019ca0f7-1604-70d5-9a43-42c05792635d

### Create auction
POST {{auction_site_api_HostAddress}}/auctions
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "title": "Test auction",
  "Description": "Auction to test ClosedAuctionResponse",
  "startPrice": 2599.00
}

### Get auction
GET {{auction_site_api_HostAddress}}/auctions/11111111-1111-1111-1111-111111111111
### Get auction
GET {{auction_site_api_HostAddress}}/auctions/22222222-2222-2222-2222-222222222222
### Get auction
GET {{auction_site_api_HostAddress}}/auctions/33333333-3333-3333-3333-333333333333

### Get auctions
GET {{auction_site_api_HostAddress}}/auctions

### Deactivate auction
PUT {{auction_site_api_HostAddress}}/auctions/33333333-3333-3333-3333-333333333333
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "isActive": fals/home/baleygr/.dev/web/labs/lab-3/auction-sitee
}

