#@auction_site_api_HostAddress = http://localhost:5220/api
@auction_site_api_HostAddress = https://api.auction.mimirsbrunnr.cloud/api
### testuser1
POST {{auction_site_api_HostAddress}}/users/register
Content-Type: application/json

{
    "username": "testuser1",
    "email": "testuser1@example.com",
    "password": "P@ssword!"
}

### Login testuser1
POST {{auction_site_api_HostAddress}}/users/login
Content-Type: application/json

{
  "usernameOrEmail": "testuser1",
  "password": "P@ssword!"
}

### testuser2 vars
@userId2 = 019ca10c-acbe-72cb-93cb-067a325797d9

### Register testuser3
POST {{auction_site_api_HostAddress}}/users/register
Content-Type: application/json

{
    "username": "testuser4",
    "email": "testuser4@example.com",
    "password": "P@ssword!"
}

### Login testuser2
POST {{auction_site_api_HostAddress}}/users/login
Content-Type: application/json

{
  "usernameOrEmail": "testuser2",
  "password": "P@ssword!"
}
### Disable testuser2
PUT {{auction_site_api_HostAddress}}/users/019ca10c-acbe-72cb-93cb-067a325797d9
Content-Type: application/json
Authorization: Bearer {{}}

{
  "isActive": false
}

### Delete tesuser
DELETE {{auction_site_api_HostAddress}}/users/019ca0f7-1604-70d5-9a43-42c05792635d

### Create auction
POST {{auction_site_api_HostAddress}}/auctions/active?search=
Content-Type: application/json
Authorization: Bearer {{}}

{
  "title": "27\" Gaming Monitor 144Hz",
  "Description": "Gaming monitor with 144Hz refresh rate and 2560x1440 resolution",
  "startPrice": 250.00
}

### Get users
GET {{auction_site_api_HostAddress}}/users

### Get auction
GET {{auction_site_api_HostAddress}}/auctions/11111111-1111-1111-1111-111111111111
### Get auction
GET {{auction_site_api_HostAddress}}/auctions/22222222-2222-2222-2222-222222222222
### Get auction
GET {{auction_site_api_HostAddress}}/auctions/33333333-3333-3333-3333-333333333333
### Get auction
GET {{auction_site_api_HostAddress}}/auctions/019cb450-d6aa-729d-bf2d-677050b5f8d6

### Get auctions
GET {{auction_site_api_HostAddress}}/auctions/active?search=
Origin: https://auction.mimirsbrunnr.cloud
### Get auctions - userid
GET {{auction_site_api_HostAddress}}/auctions?search=019ca10c-acbe-72cb-93cb-067a325797d9
### Deactivate auction
PUT {{auction_site_api_HostAddress}}/auctions/019cb450-d6aa-729d-bf2d-677050b5f8d6
Content-Type: application/json
Authorization: Bearer {{}}

{
    "isActive": false
}

### Place bid as testuser1
POST {{auction_site_api_HostAddress}}/Auctions/019cb450-d6aa-729d-bf2d-677050b5f8d6/bids
Content-Type: application/json
Authorization: Bearer {{}}

{
  "amount": 3749.00
}

### Remove latest bid
DELETE {{auction_site_api_HostAddress}}/Auctions/019cb450-d6aa-729d-bf2d-677050b5f8d6/bids/latest
Authorization: Bearer {{}}

